name: CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Docker Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - user-service
          - payment-service
          - notification-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ matrix.service }}:ci \
            ./services/${{ matrix.service }}
