name: User Service CD

on:
  push:
    branches:
      - main
    paths:
      - "services/user-service/**"
      - "ecs/task-definitions/user-service.json"
      - ".github/workflows/user-service-cd.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-3
  ECR_REPOSITORY: user-service
  ECS_CLUSTER: ecs-microservices-cluster
  ECS_SERVICE: user-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::267544548136:role/ecs-microservices-github-actions
          aws-region: ap-southeast-3
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id  : login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${GITHUB_SHA} \
            ./services/user-service

      - name: Tag image
        run: |
          docker tag \
            $ECR_REPOSITORY:${GITHUB_SHA} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${GITHUB_SHA}

      - name: Push image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${GITHUB_SHA}
